import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import robot from "../static/images/robot.png";

export default function Home() {
	return (
		<>
			<Head>
				<title>Lorem ipsum</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>

			<Image src={robot} alt="robot" className={styles.robotImage}/>

			<Navbar />
			
		</>
	);
}
